import type { Metadata } from 'next'
import { sanityDataset } from '@/environment'
import Script from 'next/script'
import ttNorms from './lib/fonts'
import SiteFooter from './components/SiteFooter'
import SiteHeader from './components/SiteHeader'
import './styles/globals.scss'

export const metadata: Metadata = {
  title: {
    template: '%s | Helix',
    default: 'Helix',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      {sanityDataset === 'staging' && (
      <>
        <Script
          id='markerConfig'
          dangerouslySetInnerHTML={{
            __html: `window.markerConfig = {
            project: '64b06db09996fc443fac798b', 
            source: 'snippet'
          }`,
          }}
        />
        <Script
          id='markerSnippet'
          dangerouslySetInnerHTML={{
          // eslint-disable-next-line
          __html: `!function(e,r,a){if(!e.__Marker){e.__Marker={};var t=[],n={__cs:t};["show","hide","isVisible","capture","cancelCapture","unload","reload","isExtensionInstalled","setReporter","setCustomData","on","off"].forEach(function(e){n[e]=function(){var r=Array.prototype.slice.call(arguments);r.unshift(e),t.push(r)}}),e.Marker=n;var s=r.createElement("script");s.async=1,s.src="https://edge.marker.io/latest/shim.js";var i=r.getElementsByTagName("script")[0];i.parentNode.insertBefore(s,i)}}(window,document);`,
          }}
        />
      </>
      )}
      <body className={ttNorms.variable}>
        {/* @ts-expect-error Async Server Component */}
        <SiteHeader />
        {children}
        {/* @ts-expect-error Async Server Component */}
        <SiteFooter />
      </body>
    </html>
  )
}
